# Generated by Django 5.2 on 2025-04-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0005_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
