# Generated by Django 5.2 on 2025-04-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0006_remove_evento_criado_em_evento_criado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-id']},
        ),
    ]
