# Generated by Django 5.2 on 2025-04-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0007_alter_evento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data']},
        ),
    ]
