# Generated by Django 5.1 on 2025-04-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0011_enquete_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
