# Generated by Django 5.1 on 2025-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0012_enquete_data_encerramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='escolha',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NÃO', 'Não')], max_length=10),
        ),
    ]
