# Generated by Django 5.2 on 2025-12-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMoradia', '0014_customuser_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
